[package]
name = "rlogmine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.1.1"
colored = "2.1.0"
tokio = { version = "1.35.1", features = ["full"] }
